create table change (
change_id integer
generated by default as identity,
active boolean,
change_type double,
date timestamp,
destination_currency_id integer,
operation varchar(255),
origin_currency_id integer,
primary key (change_id)
);
create table currency (
currency_id integer generated by default as identity,
 code varchar(255),
  name varchar(255),
  symbol varchar(255),
primary key (currency_id)
);

insert into currency(currency_id,name,code,symbol) values(1,'euro WIR','CHE','CHE');
insert into currency(currency_id,name,code,symbol) values(2,'dólar estadounidense','USD','USD');
insert into currency(currency_id,name,code,symbol) values(3,'sol peruano','PEN','S/');
insert into currency(currency_id,name,code,symbol) values(4,'franco burundés','BIF','BIF');
insert into currency(currency_id,name,code,symbol) values(5,'peso colombiano','COP','COP');
insert into currency(currency_id,name,code,symbol) values(6,'real brasileño','BRL','BRL');
insert into currency(currency_id,name,code,symbol) values(7,'libra esterlina','GBP','GBP');
insert into currency(currency_id,name,code,symbol) values(8,'peso chileno','CLP','CLP');

insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (1, 2, 3, 4.028, false, '2021-05-03 18:02:21');
insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (2, 3, 2, 0.25, false, '2021-08-17 05:47:04');
insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (3, 6, 3, 7.0, false, '2021-03-19 15:46:47');
insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (4, 5, 4, 5.29, false, '2021-07-26 08:09:25');
insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (5, 4, 5, 6.38, false, '2020-11-15 21:06:03');
insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (6, 3, 6, 5.72, false, '2020-12-06 08:06:52');
insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (7, 2, 7, 3.84, false, '2021-09-11 23:15:32');
insert into change (change_id, origin_currency_id, destination_currency_id, change_type, active, date) values (8, 1, 8, 5.17, false, '2021-07-27 17:42:54');
