create table change (
change_id integer
generated by default as identity,
change_type double,
currency_code varchar(255),
date timestamp,
primary key (change_id)
);

create table currency (
currency_id integer generated by default as identity,
 code varchar(255),
  name varchar(255),
  symbol varchar(255),
primary key (currency_id)
);

insert into currency(currency_id,name,code,symbol) values(1,'euro WIR','CHE','CHE');
insert into currency(currency_id,name,code,symbol) values(2,'dólar estadounidense','USD','USD');
insert into currency(currency_id,name,code,symbol) values(3,'sol peruano','PEN','S/');
insert into currency(currency_id,name,code,symbol) values(4,'franco burundés','BIF','BIF');
insert into currency(currency_id,name,code,symbol) values(5,'peso colombiano','COP','COP');
insert into currency(currency_id,name,code,symbol) values(6,'real brasileño','BRL','BRL');
insert into currency(currency_id,name,code,symbol) values(7,'libra esterlina','GBP','GBP');
insert into currency(currency_id,name,code,symbol) values(8,'peso chileno','CLP','CLP');

insert into change (change_type,currency_code ) values (4.028,'CHE');
insert into change (change_type,currency_code ) values (0.25,'USD');
insert into change (change_type,currency_code ) values (7.0,'PEN');
insert into change (change_type,currency_code ) values (5.29,'BIF');
insert into change (change_type,currency_code ) values (6.38,'COP');
insert into change (change_type,currency_code ) values (5.72,'BRL');
insert into change (change_type,currency_code ) values (3.84,'GBP');
insert into change (change_type,currency_code ) values (5.17,'CLP');
